---
- hosts: all
  become: yes
  tasks:
#    - name: setup apt proxy cache
#      copy:
#        dest: /etc/apt/apt.conf.d/02mirror
#        owner: root
#        mode: 0644
#        content: 'Acquire::http::Proxy "http://cato.local:3142/";'
    - name: install packages
      apt:
        update_cache: true
        state: latest
        name:
          - chrony
          - curl
          - git
          - lsof
          - python3-pip
          - rng-tools
          - rsyslog
          - screen
          - software-properties-common
          - ssh-import-id
          - vim
          - wget
    - name: install python packages
      pip:
        name:
          - black
          - isort
    - name: Add chrony sources
      when: '"greenhouse*" != "${ansible_hostname}"'
      copy:
        dest: /etc/chrony/sources.d/local.sources
        owner: root
        mode: 0644
        content: |
          # Local NTP backups
          server 10.10.10.12 iburst
          server 10.10.10.10 iburst
          pool time.google.com iburst maxsources 3
          pool pool.ntp.org iburst maxsources 3
    - name: Add me
      user:
        name: smw
        comment: Stephen Wood
        groups: sudo, adm
    - name: add github to authorized_keys
      run_once: true
      shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts
    - name: Set authorized keys for smw
      ansible.posix.authorized_key:
        user: smw
        state: present
        key: https://github.com/stephen-mw.keys
    - name: update smw keys
      shell: ssh-import-id -o ~smw/.ssh/authorized_keys gh:stephen-mw
      run_once: true
    - name: Update sshd_config
      copy:
        dest: /etc/ssh/sshd_config.d/custom
        content: |
          AllowUsers smw
          PasswordAuthentication no
          PermitRootLogin no
    - name: setup root user
      shell: cp -r /etc/skel/. /root/
      run_once: true
    - name: setup sudoers
      copy:
        dest: /etc/sudoers.d/01smw
        content: |
            smw ALL=(ALL) NOPASSWD: ALL
            # Allow sudo to keep using agent forwarding
            Defaults    env_keep+=SSH_AUTH_SOCK
    - name: custom shell
      copy:
        src: ../assets/profile.sh
        dest: /etc/profile.d/custom.sh
    - name: setup vim
      copy:
        src: ../assets/vimrc
        dest: /etc/vim/vimrc.local
    - name: vim default
      shell: update-alternatives --set editor /usr/bin/vim.basic
    - name: setup secret envs file in /etc/profile.d/secrets.sh
      copy:
        dest: /etc/profile.d/secrets.sh
        src: rpirc
    - name: setup cron
      copy:
        dest: /etc/cron.d/ansible
        owner: root
        mode: 0644
        content: |
          MAILTO=contact.stephen.wood@gmail.com
          BASH_ENV=/etc/profile.d/secrets.sh
          SHELL=/usr/bin/bash
          @daily smw github-import-id gh:stephen-mw
          @restart smw github-import-id gh:stephen-mw

