---
- hosts: all
  become: yes
  tasks:
    # Do this as soon as possible because it can cause http issues
    - name: disable ipv6
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        sysctl_set: true
        state: present
        reload: true
    - name: install packages
      apt:
        update_cache: true
        state: latest
        name:
          - chrony
          - curl
          - fzf
          - git
          - lsof
          - net-tools
          - python3-pip
          - python3-virtualenv
          - rng-tools
          - rsyslog
          - screen
          - software-properties-common
          - ssh-import-id
          - unp
          - vim
          - wget
    - name: add github known host key
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ item }}"
        path: /etc/ssh/ssh_known_hosts
        state: present
      loop:
          - github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          - github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          - github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    - name: Set authorized keys for smw
      ansible.posix.authorized_key:
        user: smw
        state: present
        key: https://github.com/stephen-mw.keys
    - name: remove apparmor
      apt:
        state: absent
        name:
          - apparmor
    - name: Remove popularity contest
      ansible.builtin.file:
        path: /etc/cron.daily/popularity-contest
        state: absent
    - name: install python packages
      pip:
        name:
          - black
          - isort
    - name: install golang
      script: install_golang
      environment:
        ARCH: "{{ ansible_architecture }}"
        VERSION: "1.20.7"
    - name: Add sudo/adm group
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
        system: true
      loop:
        - adm
        - sudo
    - name: Add chrony sources
      when: '"greenhouse*" != "${ansible_hostname}"'
      copy:
        dest: /etc/chrony/sources.d/local.sources
        owner: root
        mode: 0644
        content: |
          # Local NTP backups
          server 10.10.10.12 iburst
          server 10.10.10.10 iburst
          pool time.google.com iburst maxsources 3
          pool pool.ntp.org iburst maxsources 3
    - name: Add me
      user:
        name: smw
        comment: Stephen Wood
        groups: sudo, adm
        shell: /bin/bash
    - name: update smw keys
      shell: ssh-import-id -o ~smw/.ssh/authorized_keys gh:stephen-mw
      run_once: true
    - name: setup root user
      shell: cp -r /etc/skel/. /root/
      run_once: true
    - name: setup sudoers
      copy:
        dest: /etc/sudoers.d/01smw
        content: |
            smw ALL=(ALL) NOPASSWD: ALL
            # Allow sudo to keep using agent forwarding
            Defaults    env_keep+=SSH_AUTH_SOCK
    - name: custom shell
      copy:
        src: ../assets/profile.sh
        dest: /etc/profile.d/custom.sh
    - name: setup vim
      copy:
        src: ../assets/vimrc
        dest: /etc/vim/vimrc.local
    - name: vim default
      shell: update-alternatives --set editor /usr/bin/vim.basic
    - name: setup secret envs file in /etc/profile.d/secrets.sh
      copy:
        dest: /etc/profile.d/secrets.sh
        src: rpirc
    - name: setup cron
      copy:
        dest: /etc/cron.d/ansible
        owner: root
        mode: 0644
        content: |
          MAILTO=contact.stephen.wood@gmail.com
          BASH_ENV=/etc/profile.d/secrets.sh
          SHELL=/usr/bin/bash
          @daily smw /usr/bin/ssh-import-id gh:stephen-mw
          @restart smw /usr/bin/ssh-import-id gh:stephen-mw
    - name: lock down sshd
      copy:
        dest: /etc/ssh/sshd_config.d/ansible
        owner: root
        mode: 0644
        content: |
          Include /etc/ssh/sshd_config.d/*.conf
          AllowUsers smw
          PasswordAuthentication no
          UseDNS no
          X11Forwarding yes
          X11UseLocalhost no
          AddressFamily inet
    - name: allow dmesg for all
      ansible.posix.sysctl:
        name: kernel.dmesg_restrict
        value: '0'
        sysctl_set: true
        state: present
        reload: true
