---
- hosts: all
  become: yes
  tasks:
    - name: setup apt proxy cache
      copy:
        dest: /etc/apt/apt.conf.d/02mirror
        owner: root
        mode: 0644
        content: 'Acquire::http::Proxy "http://cato.local:3142/";'
    - name: install packages
      apt:
        state: present
        name:
          - curl
          - git
          - ntp
          - python3
          - python3-pip
          - rng-tools
          - rsyslog
          - screen
          - software-properties-common
          - ssh-import-id
          - vim
          - wget
    - name: Add me
      user:
        name: smw
        comment: Stephen Wood
        groups: sudo, adm
    - name: update smw keys
      shell: ssh-import-id -o ~smw/.ssh/.authorized_keys gh:stephen-mw
      run_once: true
    - name: Update sshd_config
      copy:
        dest: /etc/ssh/sshd_config
        content: |
          AllowUsers smw
          PasswordAuthentication no
          PermitRootLogin no
    - name: setup root user
      shell: cp -r /etc/skel/. /root/
      run_once: true
    - name: setup sudoers
      copy:
        dest: /etc/sudoers.d/01smw
        content: |
            smw ALL=(ALL) NOPASSWD: ALL
            # Allow sudo to keep using agent forwarding
            Defaults    env_keep+=SSH_AUTH_SOCK
    - name: setup vim
      copy:
        src: ../vimrc
        dest: /etc/vim/vimrc.local
    - name: vim default
      shell: update-alternatives --set editor /usr/bin/vim.basic
      run_once: true
    - name: setup shell
      copy:
        dest: /etc/profile.d/custom.sh
        content: |
          # Better ls command
          alias ll="ls -ltr"

          # make less case insensitive for searches and display verbose prompt by default
          export LESS="-irMS"

          # Add terminal colors
          export CLICOLOR=1

          # Don't put duplicate lines in the history. also, don't save lines that begin
          # with a whitespace character
          export HISTCONTROL=erasedups:ignorespace
          export HISTTIMEFORMAT='%F %T '
          export HISTSIZE=20000
          shopt -s histappend

          # Make the bash history save for all open terminals
          export PROMPT_COMMAND='history -a'

          # Collapses multi-line commands into a single history item
          shopt -s cmdhist

          # ignore these short commands in the history
          export HISTIGNORE="&:cd:fg:bg:pwd:pd:po:pushd:popd:dirs:ls:jobs:top"
    - name: setup cron
      copy:
        dest: /etc/cron.d/ansible
        owner: root
        mode: 0644
        content: |
          MAILTO=contact.stephen.wood@gmail.com
          BASH_ENV=/etc/environment.d/secret
          SHELL=/usr/bin/bash
          @daily smw githu-import-id gh:stephen-mw
          @restart smw githu-import-id gh:stephen-mw
    - name: setup rpirc in /etc/environment
      blockinfile:
        insertbefore: bof
        dest: /etc/environment
        block: "{{ lookup('file', 'rpirc') }}"
