---
- hosts: all
  become: yes
  tasks:
    - name: setup rsyslog receiving
      copy:
        dest: /etc/rsyslog.d/00-cato.conf
        owner: root
        mode: 0644
        content: |
          # provides UDP syslog reception
          module(load="imudp")
          input(type="imudp" port="514")

          # provides TCP syslog reception
          module(load="imtcp")
          input(type="imtcp" port="514")

          # Log remote hosts to separate log file
          $template PerHostLog,"/var/log/remote/%HOSTNAME%.log"
          $template RemoteHostFileFormat,"%TIMESTAMP% %HOSTNAME% %syslogfacility-text% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::space-cc,drop-last-lf%\n"
          :inputname, isequal, "imudp" ?PerHostLog;RemoteHostFileFormat
          & stop
