#!/usr/bin/env bash
set -euo pipefail


export VERSION="2.61-1"

# Support for 32 bit, 64 bit ARM
if [[ "${ARCH}" == "armv7l" || "${ARCH}" == "armv6l" ]]; then
  ARCH="armhf"
elif [[ "${ARCH}" == "aarch64" ]]; then
  ARCH="arm64"
else
  echo "non-compatible architecture version: ${ARCH}"
  exit 1
fi

if [[ $(dpkg -l wiringpi) ]]; then
    echo "Wiring pi already installed"
    exit
fi

cd /tmp
export FILE_URI="https://github.com/WiringPi/WiringPi/releases/download/${VERSION}/wiringpi-${VERSION}-${ARCH}.deb"

echo "Downloading ${FILE_URI}"
wget "${FILE_URI}"
dpkg -i wiringpi-${VERSION}-${ARCH}.deb
