---
- hosts: all
  become: yes
  tasks:
    - name: setup apt proxy cache
      copy:
        dest: /etc/apt/apt.conf.d/02mirror
        owner: root
        mode: 0644
        content: '#Acquire::http::Proxy "http://cato.local:3142/";'
    - name: set RPI hostname
      # This will make it so the dhcp-set hostname will take effect.
      run_once: true
      copy:
        dest: /etc/hostname
        content: localhost
    - name: remove piwiz
      apt:
        state: absent
        name:
          - piwiz
    - name: install packages
      apt:
        update_cache: true
        state: present
        install_recommends: false
        name:
          - i2c-tools
          - libsox-fmt-mp3
          - pavucontrol
          - rpi-update
          - sox
          - watchdog
          - xinit
          - xserver-xorg
    - name: setup watchdog
      blockinfile:
        dest: /etc/watchdog.conf
        content: |
          realtime		= yes
          priority		= 1
          watchdog-device = /dev/watchdog
          watchdog-timeout = 15
          max-load-1 = 24
          interface = wlan0
    - name: start watchdog
      ansible.builtin.systemd:
        name: watchdog
        enabled: true
        state: stopped
    - name: setup swood to updated groups
      user:
        name: smw
        comment: Stephen Wood
        groups:
          - adm
          - bluetooth
          - i2c
          - sudo
    - name: Remove the default pi user
      user:
        name: pi
        state: absent
        remove: yes
        force: true
    - name: setup syslog
      copy:
        dest: /etc/rsyslog.d/custom.conf
        content: '*.*  @cato.u1f602.com:514'
    - name: disable ipv6
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          # Disable ipv6
          net.ipv6.conf.all.disable_ipv6 = 1
    - name: enable RNG config
      blockinfile:
        path: /etc/default/rng-tools-debian
        block: |
          HRNGDEVICE=/dev/hwrng
    - name: Setup boot.txt
      blockinfile:
        dest: /boot/config.txt
        marker: "### rpi.yml ansible block ###"
        block: |
          [all]
          dtparam=watchdog=on
    - name: load i2c in modules
      blockinfile:
        dest: /etc/modules-load.d/modules.conf
        content: i2c-dev
    - name: Enable systemd watchdog
      blockinfile:
        path: /etc/systemd/system.conf
        backup: yes
        block: |
          RuntimeWatchdogSec=10
          ShutdownWatchdogSec=10min
          RebootWatchdogSec=10min
          WatchdogDevice=/dev/watchdog
    - name: disable swap
      ansible.builtin.systemd:
        masked: true
        name: dphys-swapfile
    - name: setup unattended upgrades
      apt:
        state: present
        name:
          - apt-listchanges
          - bsd-mailx
          - unattended-upgrades
    - name: setup /etc/apt/apt.conf.d/50unattended-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Mail "contact.stephen.wood@gmail.com";
          Unattended-Upgrade::Automatic-Reboot "true";
          Unattended-Upgrade::Automatic-Reboot-Time "14:00";
    - name: setup /etc/apt/apt.conf.d/20auto-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::Verbose "1";
          APT::Periodic::AutocleanInterval "7";
    - name: enable unattended upgrades
      run_once: true
      shell: "dpkg-reconfigure --priority=low unattended-upgrades -fnoninteractive"
    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: true
    - name: Disable auto-login
      ansible.builtin.file:
        path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        state: absent
    - name: install wiring pi
      script: install_wiringpi
      environment:
        ARCH: "{{ ansible_facts['architecture'] }}"
