---
- hosts: all
  become: yes
  tasks:
    - name: setup apt proxy cache
      copy:
        dest: /etc/apt/apt.conf.d/02mirror
        owner: root
        mode: 0644
        content: '#Acquire::http::Proxy "http://cato.local:3142/";'
    - name: set RPI hostname
      # This will make it so the dhcp-set hostname will take effect.
      run_once: true
      copy:
        dest: /etc/hostname
        content: localhost
#    - name: add debian keys
#      run_once: true
#      shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 648ACFD622F3D138 0E98404D386FA1D9 605C66F00D6C9793 9165938D90FDDD2E
#    - name: Update apt sources
#      copy:
#        dest: /etc/apt/sources.list
#        content: |
#          # Old mirrors
#          deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi
#          #deb-src http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi
#          deb http://archive.raspberrypi.org/debian/ bullseye main
#          #deb-src http://archive.raspberrypi.org/debian/ bullseye main
#
#          # Local mirrors
#          #deb http://mirror.u1f602.com/debian/ bullseye main
#          #deb http://mirror.u1f602.com/raspbian/ bullseye main contrib non-free rpi
#          #deb-src http://mirror.u1f602.com/debian/ bullseye main
#          #deb-src http://mirror.u1f602.com/raspbian/ bullseye main contrib non-free rpi
#    - name: Upgrade once to latest version
#      run_once: true
#      apt:
#        upgrade: dist
#    - name: Remove old list
#      ansible.builtin.file:
#        path: /etc/apt/sources.list.d/raspi.list
#        state: absent
    - name: remove piwiz
      apt:
        state: absent
        name:
          - piwiz
    - name: install packages
      apt:
        update_cache: true
        state: present
        install_recommends: false
        name:
          - i2c-tools
          - libsox-fmt-mp3
          - pavucontrol
          - pigpio
          - rpi-update
          - sox
          - wiringpi
          - xinit
          - xserver-xorg
    - name: setup watchdog
      blockinfile:
        dest: /etc/watchdog.conf
        content: |
          realtime		= yes
          priority		= 1
          watchdog-device = /dev/watchdog
          watchdog-timeout = 15
          max-load-1 = 24
          interface = wlan0
    # TODO this is not yet working
    # https://github.com/RPi-Distro/repo/issues/237
    - name: start watchdog
      ansible.builtin.systemd:
        name: watchdog
        enabled: true
        state: stopped
# This currently breaks the pi's bluetooth
#    - name: Upgrade RPI firmware
#      run_once: true
#      shell: yes | rpi-update || true
    - name: setup swood to updated groups
      user:
        name: smw
        comment: Stephen Wood
        groups:
          - adm
          - bluetooth
          - gpio
          - i2c
          #- pulse-access
          - sudo
    - name: Remove the default pi user
      user:
        name: pi
        state: absent
        remove: yes
        force: true
    - name: setup syslog
      copy:
        dest: /etc/rsyslog.d/custom.conf
        content: '*.*  @cato.u1f602.com:514'
    - name: disable ipv6
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          # Disable ipv6
          net.ipv6.conf.all.disable_ipv6 = 1
    - name: enable RNG config
      blockinfile:
        path: /etc/default/rng-tools-debian
        block: |
          HRNGDEVICE=/dev/hwrng
    - name: Setup boot.txt
      blockinfile:
        path: /boot/config.txt
        block: |
          [all]
          dtparam=watchdog=on
          dtparam=i2c_arm=on
    - name: Enable systemd watchdog
      blockinfile:
        path: /etc/systemd/system.conf
        backup: yes
        block: |
          RuntimeWatchdogSec=10
          ShutdownWatchdogSec=10min
          RebootWatchdogSec=10min
          WatchdogDevice=/dev/watchdog
#    - name: setup unattended upgrades
#      apt:
#        state: present
#        name:
#          - apt-listchanges
#          - bsd-mailx
#          - unattended-upgrades
#    - name: setup /etc/apt/apt.conf.d/50unattended-upgrades
#      copy:
#        dest: /etc/apt/apt.conf.d/50unattended-upgrades
#        content: |
#          Unattended-Upgrade::Mail "contact.stephen.wood@gmail.com";
#          Unattended-Upgrade::Automatic-Reboot "true";
#          Unattended-Upgrade::Automatic-Reboot-Time "14:00";
#    - name: setup /etc/apt/apt.conf.d/20auto-upgrades
#      copy:
#        dest: /etc/apt/apt.conf.d/20auto-upgrades
#        content: |
#          APT::Periodic::Update-Package-Lists "1";
#          APT::Periodic::Download-Upgradeable-Packages "1";
#          APT::Periodic::Unattended-Upgrade "1";
#          APT::Periodic::Verbose "1";
#          APT::Periodic::AutocleanInterval "7";
#    - name: enable unattended upgrades
#      run_once: true
#      shell: "dpkg-reconfigure --priority=low unattended-upgrades -fnoninteractive"
    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: true
    - name: Disable auto-login
      ansible.builtin.file:
        path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        state: absent
