---
- hosts: all
  become: yes
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: vps
        use: systemd
    - name: Update /etc/hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1 vps
    - name: install packages
      apt:
        update_cache: true
        state: latest
        name:
          - certbot
          - firewall-config
          - firewalld
          - nginx
          - python3-certbot-nginx
    - name: permit traffic for http/https/ssh
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
        - ntp
        - ssh
    - name: permit rtorrent
      ansible.posix.firewalld:
        port: 49164/tcp
        permanent: true
        state: enabled
