#!/usr/bin/env bash
set -euo pipefail

# Don't reinstall if it already exists
export VERSION=3.25
if gpsd --version | grep -q ${VERSION}; then
    echo "gpsd already installed at ${VERSION}"
    exit
fi

# Most of the python libraries below are for using xgps, and can be skipped
# if you don't plan to run xgps
sudo apt remove -y --purge gpsd
sudo apt install -y    \
    build-essential    \
    libdbus-1-dev      \
    libgtk-3-dev       \
    libncurses5-dev    \
    manpages-dev       \
    pkg-config         \
    pps-tools          \
    python-dev         \
    python-gi-dev      \
    python3-cairo      \
    python3-gi-cairo   \
    python3-matplotlib \
    python3-serial     \
    scons

export URI="http://download.savannah.gnu.org/releases/gpsd/gpsd-${VERSION}.zip"

cd /tmp
rm -rfv gpsd-${VERSION} || true
wget ${URI}
unp gpsd-${VERSION}.zip
cd gpsd-${VERSION}

# Install the software
scons -c
scons
scons check
scons install
