---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      apt:
        update_cache: true
        state: present
        name:
          - chrony
          - pps-tools
          - gpsd
    - name: compile gpsd
      script: compile_gpsd
    - name: set PYTHONPATH for xgps
      blockinfile:
        dest: /etc/bash.bashrc
        content: "export PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/"
    - name: setup chrony conf
      copy:
        src: ./chrony.conf
        dest: /etc/chrony/chrony.conf
    - name: setup chrony service
      copy:
        src: ./chrony.service
        dest: /etc/systemd/system/chrony.service
    - name: setup gpsd systemd service
      copy:
        src: ./gpsd.service
        dest: /etc/systemd/system/gpsd.service
        mode: 0644
    - name: enable modules for ntp
      copy:
        dest: /etc/modules-load.d/ntp.server
        content: |
          pps-gpio
          i2c-dev
          rtc-ds1307
    # setup i2c, serial, and rtc
    - name: enable modules for ntp
      blockinfile:
        dest: /boot/config.txt
        content: |
          dtparam=watchdog=on
          dtoverlay=pps-gpio,gpiopin=18
          dtparam=i2c1=on
          dtoverlay=i2c-rtc,ds1307
          enable_uart=1
    # This is the correct serial port for debian bookworm+
    - name: setup gpsd options
      blockinfile:
        dest: /etc/default/gpsd
        content: DEVICES="/dev/serial0"
    # i2c check file
    - name: setup chrony service
      copy:
        src: i2c_check
        dest: /usr/bin/i2c_check
        mode: 0755
        owner: root
        group: root
    - name: start gpsd
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - gpsd
        - chrony
