---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      apt:
        update_cache: true
        state: present
        name:
          - chrony
          - pps-tools
    - name: compile gpsd
      script: compile_gpsd
    - name: set PYTHONPATH for xgps
      blockinfile:
        dest: /etc/bash.bashrc
        content: "export PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/"
#    - name: setup chrony conf
#      copy:
#        src: ./chrony.conf
#        dest: /etc/chrony/chrony.conf
    - name: setup chrony service
      copy:
        src: ./chrony.service
        dest: /etc/systemd/system/chrony.service
    - name: setup gpsd systemd service
      copy:
        src: ./gpsd.service
        dest: /etc/systemd/system/gpsd.service
        mode: 0644
    - name: start gpsd
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - gpsd
        - chrony
    # i2c check file
    - name: setup chrony service
      copy:
        src: i2c_check
        dest: /usr/bin/i2c_check
        mode: 0744
        owner: root
        group: root
