#!/usr/bin/env bash
set -euo pipefail

# For this to work you need to download the linux-UFRII-drv-v570-us drivers
# directly from Canon and put them in the root directory.
if [[ -d "/usr/local/src/linux-UFRII-drv-v570-us" ]]; then
    echo "Drivers already present. Refusing to install."
    exit
fi

# Sanity check that env variable set by ansible
echo "Using drivers located at ${DRIVERS}"

cd /usr/local/src
tar xvf linux-UFRII-drv-v570-us-18.tar.gz
cd linux-UFRII-drv-v570-us
sudo dpkg -i -G --force-overwrite ARM64/Debian/cnrdrvcups-ufr2-us_*.deb
