---
- name: scanner playbook
  hosts: all
  become: yes
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: 'scanny'
    - name: install packages
      apt:
        update_cache: true
        state: present
        name:
          - cups
          - libsane1
          - libcups2
          - printer-driver-gutenprint
          - sane
          - sane-utils
    - name: setup canon printer drivers
      ansible.builtin.copy:
        src: linux-UFRII-drv-v570-us-18.tar.gz
        dest: /usr/local/src/
    # This will exit code failure the first time
    - name: install drivers
      script: install_drivers
      environment:
        DRIVERS: "linux-UFRII-drv-v570-us-18"
    - name: create user
      ansible.builtin.user:
        name: scanny
        shell: /usr/sbin/nologin
        system: yes
        groups:
          - lp
          - lpadmin
        password: "{{ scanny_password }}"
        createhome: yes
        home: /etc/scanny
    - name: Allow anyone to print
      command: cupsctl --remote-any
    - name: Make sure scanny user can modify/admin CUPS
      replace:
        path: /etc/cups/cupsd.conf
        regexp: '^    Require user @SYSTEM'
        replace: '    Require user @SYSTEM scanny'
    - name: Add scan command script
      copy:
        dest: /usr/local/bin/scan
        content: |
          #!/usr/bin/env bash
          set -euo pipefail
          # If it says "device busy" you need to set scan / remote scan on the printer
          sudo scanimage -d "pixma:04A92775_1128L3600730" --resolution=75 --format=png > "$(date +%s).png"
        mode: '0770'
        owner: root
        group: smw
    - name: Customize CUPS configuration
      blockinfile:
        path: /etc/cups/cupsd.conf
        block: |
          <Location />
            Order allow,deny
            Allow from 10.10.10.0/24
          </Location>
    - name: add caddy config
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
            :80 {
              reverse_proxy localhost:631
            }
            # Refer to the Caddy docs for more information:
            # https://caddyserver.com/docs/caddyfile
        owner: root
        group: caddy
        mode: 640
