---
- name: scanner playbook
  hosts: all
  become: yes
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: 'scanny'
    - name: install packages
      apt:
        update_cache: true
        state: present
        name:
          - cups
          - libsane1
          - libcups2
          - printer-driver-gutenprint
          - sane-utils
    - name: setup canon printer drivers
      ansible.builtin.copy:
        src: linux-UFRII-drv-v570-us-18.tar.gz
        dest: /usr/local/src/
    # This will exit code failure the first time
    - name: install drivers
      script: install_drivers
      environment:
        DRIVERS: "linux-UFRII-drv-v570-us-18"
    - name: create user
      ansible.builtin.user:
        name: scanny
        shell: /usr/sbin/nologin
        system: yes
        groups:
          - lp
          - lpadmin
        password: "{{ scanny_password }}"
        createhome: yes
        home: /etc/scanny
    - name: Allow anyone to print
      command: cupsctl --remote-any
    - name: Make sure scanny user can modify/admin CUPS
      replace:
        path: /etc/cups/cupsd.conf
        regexp: '^    Require user @SYSTEM'
        replace: '    Require user @SYSTEM scanny'
    - name: Add scan command script
      copy:
        dest: /usr/local/bin/scan
        content: |
          #!/usr/bin/env bash
          set -euo pipefail
          # If it says "device busy" you need to set scan / remote scan on the printer
          sudo scanimage -d "pixma:04A92775_1128L3600730" --resolution=75 --format=png > "$(date +%s).png"
        mode: '0770'
        owner: root
        group: smw
    - name: Restrict CUPS access to local subnet
      replace:
        path: /etc/cups/cupsd.conf
        regexp: 'Allow all'
        replace: 'Allow from 10.10.10.0/24'
    - name: Set CUPS to listen on port 80
      lineinfile:
        path: /etc/cups/cupsd.conf
        regexp: '^Port 631'
        line: 'Port 80'
    - name: Enable CUPS web interface
      lineinfile:
        path: /etc/cups/cupsd.conf
        regexp: '^WebInterface'
        line: 'WebInterface Yes'
    - name: Enable CUPS browsing
      lineinfile:
        path: /etc/cups/cupsd.conf
        regexp: '^Browsing'
        line: 'Browsing Yes'
    - name: Add D530 printer
      command: lpadmin -p D530 -E -v "usb://Canon/D530/D560?serial=1128L3600730&interface=1" -m "canonufr2-drv:0/cnd530.ppd"
      args:
        creates: /etc/cups/ppd/D530.ppd
    - name: Share D530 printer
      command: lpadmin -p D530 -o printer-is-shared=true
    - name: Set default paper size to Letter
      command: lpadmin -p D530 -o PageSize=Letter
